export const GET_COUNTRIES_OKRB_TOP_AMOUNT_REQUEST = 'GET_COUNTRIES_OKRB_TOP_AMOUNT_REQUEST'
export const GET_COUNTRIES_OKRB_TOP_AMOUNT_SUCCESS = 'GET_COUNTRIES_OKRB_TOP_AMOUNT_SUCCESS'
export const GET_COUNTRIES_OKRB_TOP_AMOUNT_FAILURE = 'GET_COUNTRIES_OKRB_TOP_AMOUNT_FAILURE'
export const GET_COUNTRIES_OKRB_TOP_AMOUNT_CLEAR = 'GET_COUNTRIES_OKRB_TOP_AMOUNT_CLEAR'

export const GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_REQUEST = 'GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_REQUEST'
export const GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_SUCCESS = 'GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_SUCCESS'
export const GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_FAILURE = 'GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_FAILURE'
export const GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_CLEAR = 'GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT_CLEAR'

export const GET_BELARUS_PRODUCTS_SHARE_REQUEST = 'GET_BELARUS_PRODUCTS_SHARE_REQUEST'
export const GET_BELARUS_PRODUCTS_SHARE_SUCCESS = 'GET_BELARUS_PRODUCTS_SHARE_SUCCESS'
export const GET_BELARUS_PRODUCTS_SHARE_FAILURE = 'GET_BELARUS_PRODUCTS_SHARE_FAILURE'
export const GET_BELARUS_PRODUCTS_SHARE_CLEAR = 'GET_BELARUS_PRODUCTS_SHARE_CLEAR'


// export const BUY_BELARUSIAN = [
//   {
//     type: 'GET_PRODUCT_COUNTRIES_CONTRACT_ITEMS_AMOUNT',
//     value: 'productCountriesContractItemsAmount',
//   },
//   {
//     type: 'GET_COUNTRIES_OKRB_TOP_AMOUNT',
//     value: 'countriesOkrbTopAmount',
//   },
// ]
