Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Беларусь','Беларусь','BLR','BY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Российская Федерация','Российская Федерация','RUS','RU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Переходное Исламское Государство Афганистан','Афганистан','AFG','AF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Албания','Албания','ALB','AL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Антарктида','Антарктида','ATA','AQ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Алжирская Народная Демократическая Республика','Алжир','DZA','DZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Американское Самоа','Американское Самоа','ASM','AS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Княжество Андорра ','Андорра','AND','AD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Ангола','Ангола','AGO','AO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Антигуа и Барбуда','Антигуа и Барбуда','ATG','AG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Азербайджан','Азербайджан','AZE','AZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Аргентинская Республика','Аргентина','ARG','AR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Австралия','Австралия','AUS','AU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Австрийская Республика ','Австрия','AUT','AT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Содружество Багамы ','Багамы','BHS','BS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Государство Бахрейн ','Бахрейн','BHR','BH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Народная Республика Бангладеш','Бангладеш','BGD','BD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Армения','Армения','ARM','AM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Барбадос','Барбадос','BRB','BB');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Бельгия','Бельгия','BEL','BE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Бермуды','Бермуды','BMU','BM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Бутан ','Бутан','BTN','BT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Многонациональное Государство Боливия','Боливия, Многонациональное Государство','BOL','BO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Босния и Герцеговина','Босния и Герцеговина','BIH','BA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республики Ботсвана','Ботсвана','BWA','BW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Остров Буве','Остров Буве','BVT','BV');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративная Республика Бразилия','Бразилия','BRA','BR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Белиз','Белиз','BLZ','BZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Британская Территория в Индийском Океане','Британская Территория в Индийском Океане','IOT','IO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Соломоновы Острова','Соломоновы Острова','SLB','SB');
Insert into countries (name, short_name, iso_3, iso_2) values ('Британские Виргинские Острова','Виргинские Острова, Британские','VGB','VG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Государство Бруней-Даруссалам ','Бруней-Даруссалам','BRN','BN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Болгария ','Болгария','BGR','BG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Союз Мьянма ','Мьянма','MMR','MM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Бурунди','Бурунди','BDI','BI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Камбоджа ','Камбоджа','KHM','KH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Камерун','Камерун','CMR','CM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Канада','Канада','CAN','CA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Кабо-Верде','Кабо-Верде','CPV','CV');
Insert into countries (name, short_name, iso_3, iso_2) values ('Острова Кайман','Острова Кайман','CYM','KY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Центральноафриканская Республика','Центральноафриканская Республика','CAF','CF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Демократическая Социалистическая Республика Шри-Ланка','Шри-Ланка','LKA','LK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Чад','Чад','TCD','TD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Чили','Чили','CHL','CL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Китайская Народная Республика','Китай','CHN','CN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Тайвань (Китай)','Тайвань (Китай)','TWN','TW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Остров Рождества','Остров Рождества','CXR','CX');
Insert into countries (name, short_name, iso_3, iso_2) values ('Кокосовые (Килинг) Острова','Кокосовые (Килинг) Острова','CCK','CC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Колумбия','Колумбия','COL','CO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Союз Коморы','Коморы','COM','KM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Майотта','Майотта','MYT','YT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Конго','Конго','COG','CG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Демократическая Республика Конго','Конго, Демократическая Республика','COD','CD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Острова Кука','Острова Кука','COK','CK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Коста-Рика ','Коста-Рика','CRI','CR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Хорватия ','Хорватия','HRV','HR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Куба ','Куба','CUB','CU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Кипр ','Кипр','CYP','CY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Чешская Республика ','Чехия','CZE','CZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Народная Республика Бенин','Бенин','BEN','BJ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Дания ','Дания','DNK','DK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Содружество Доминики','Доминика','DMA','DM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Доминиканская Республика','Доминиканская Республика','DOM','DO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Эквадор ','Эквадор','ECU','EC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Эль-Сальвадор','Эль-Сальвадор','SLV','SV');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Экваториальная Гвинея','Экваториальная Гвинея','GNQ','GQ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративная Демократическая Республика Эфиопия','Эфиопия','ETH','ET');
Insert into countries (name, short_name, iso_3, iso_2) values ('Государство Эритрея','Эритрея','ERI','ER');
Insert into countries (name, short_name, iso_3, iso_2) values ('Эстонская Республика','Эстония','EST','EE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Фарерские Острова','Фарерские Острова','FRO','FO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Фолклендские Острова (Мальвинские)','Фолклендские Острова (Мальвинские)','FLK','FK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Южная Георгия и Южные Сандвичевы Острова','Южная Джорджия и Южные Сандвичевы Острова','SGS','GS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Островов Фиджи','Фиджи','FJI','FJ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Финляндская Республика ','Финляндия','FIN','FI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Французская Республика','Франция','FRA','FR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Французская Гвиана','Французская Гвиана','GUF','GF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Французская Полинезия','Французская Полинезия','PYF','PF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Французские Южные Территории','Французские Южные Территории','ATF','TF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Джибути ','Джибути','DJI','DJ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Габонская Республика','Габон','GAB','GA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Грузия','Грузия','GEO','GE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гамбия','Гамбия','GMB','GM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративная Республика Германия','Германия','DEU','DE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гана ','Гана','GHA','GH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гибралтар','Гибралтар','GIB','GI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Кирибати','Кирибати','KIR','KI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Греческая Республика','Греция','GRC','GR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гренландия','Гренландия','GRL','GL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гренада','Гренада','GRD','GD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гваделупа','Гваделупа','GLP','GP');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гуам','Гуам','GUM','GU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гватемала ','Гватемала','GTM','GT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гвинейская Республика ','Гвинея','GIN','GN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гайана ','Гайана','GUY','GY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гаити','Гаити','HTI','HT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Остров Херд и Острова Макдональд','Остров Херд и Острова Макдональд','HMD','HM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Папский Престол','Папский Престол','VAT','VA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гондурас ','Гондурас','HND','HN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Венгрия','Венгрия','HUN','HU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Исландия','Исландия','ISL','IS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Индия ','Индия','IND','IN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Индонезия ','Индонезия','IDN','ID');
Insert into countries (name, short_name, iso_3, iso_2) values ('Исламская Республика Иран','Иран, Исламская Республика','IRN','IR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Ирак','Ирак','IRQ','IQ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Ирландия','Ирландия','IRL','IE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Государство Израиль ','Израиль','ISR','IL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Итальянская Республика ','Италия','ITA','IT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Ямайка','Ямайка','JAM','JM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Япония','Япония','JPN','JP');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Казахстан','Казахстан','KAZ','KZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Иорданское Хашимитское Королевство','Иордания','JOR','JO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Кения','Кения','KEN','KE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Корейская Народно-Демократическая Республика','Корея, Народно-Демократическая Республика','PRK','KP');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Корея','Корея, Республика','KOR','KR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Государство Кувейт','Кувейт','KWT','KW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Кыргызская Республика','Кыргызстан','KGZ','KG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Лаосская Народно-Демократическая Республика','Лаосская Народно-Демократическая Республика','LAO','LA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Ливанская Республика','Ливан','LBN','LB');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Лесото','Лесото','LSO','LS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Латвийская Республика','Латвия','LVA','LV');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Либерия','Либерия','LBR','LR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Ливия','Ливия','LBY','LY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Княжество Лихтенштейн','Лихтенштейн','LIE','LI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Литовская Республика','Литва','LTU','LT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Великое Герцогство Люксембург','Люксембург','LUX','LU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Специальный административный район Китая Макао','Макао','MAC','MO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Мадагаскар ','Мадагаскар','MDG','MG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Малави','Малави','MWI','MW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Малайзия','Малайзия','MYS','MY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Мальдивская Республика ','Мальдивы','MDV','MV');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Мали ','Мали','MLI','ML');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Мальта','Мальта','MLT','MT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Мартиника','Мартиника','MTQ','MQ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Исламская Республика Мавритания','Мавритания','MRT','MR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Маврикий','Маврикий','MUS','MU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Мексиканские Соединенные Штаты','Мексика','MEX','MX');
Insert into countries (name, short_name, iso_3, iso_2) values ('Княжество Монако','Монако','MCO','MC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Монголия','Монголия','MNG','MN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Молдова','Молдова, Республика','MDA','MD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Монтсеррат','Монтсеррат','MSR','MS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Марокко ','Марокко','MAR','MA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Мозамбик ','Мозамбик','MOZ','MZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Султанат Оман ','Оман','OMN','OM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Намибия ','Намибия','NAM','NA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Науру ','Науру','NRU','NR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративная Демократическая Республика Непал','Непал','NPL','NP');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Нидерландов','Нидерланды','NLD','NL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Аруба','Аруба','ABW','AW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Новая Каледония','Новая Каледония','NCL','NC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Вануату','Вануату','VUT','VU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Новая Зеландия','Новая Зеландия','NZL','NZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Никарагуа','Никарагуа','NIC','NI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Нигер','Нигер','NER','NE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративная Республика Нигерия','Нигерия','NGA','NG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Ниуэ','Ниуэ','NIU','NU');
Insert into countries (name, short_name, iso_3, iso_2) values ('Остров Норфолк','Остров Норфолк','NFK','NF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Норвегия','Норвегия','NOR','NO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Содружество Северных Марианских Островов','Северные Марианские Острова','MNP','MP');
Insert into countries (name, short_name, iso_3, iso_2) values ('Малые Тихоокеанские Отдаленные Острова Соединенных Штатов','Малые Тихоокеанские Отдаленные Острова Соединенных Штатов','UMI','UM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративные Штаты Микронезии','Микронезия, Федеративные Штаты','FSM','FM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Маршалловы Острова','Маршалловы Острова','MHL','MH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Палау','Палау','PLW','PW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Исламская Республика Пакистан','Пакистан','PAK','PK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Панама','Панама','PAN','PA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Независимое Государство Папуа–Новая Гвинея','Папуа–Новая Гвинея','PNG','PG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Парагвай ','Парагвай','PRY','PY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Перу ','Перу','PER','PE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Филиппины','Филиппины','PHL','PH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Питкэрн','Питкэрн','PCN','PN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика  Польша','Польша','POL','PL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Португальская Республика ','Португалия','PRT','PT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Гвинея-Бисау','Гвинея-Бисау','GNB','GW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Демократическая Республика Тимор-Лесте','Тимор-Лесте','TMP','TP');
Insert into countries (name, short_name, iso_3, iso_2) values ('Пуэрто-Рико','Пуэрто-Рико','PRI','PR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Государство Катар','Катар','QAT','QA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Реюньон','Реюньон','REU','RE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Румыния','Румыния','ROM','RO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Руандийская Республика','Руанда','RWA','RW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Святая Елена, остров Вознесения и Тристан-да-Кунья','Святая Елена, остров Вознесения и Тристан-да-Кунья','SHN','SH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федерация Сент-Китс и Невис','Сент-Китс и Невис','KNA','KN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Ангилья','Ангилья','AIA','AI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сент-Люсия','Сент-Люсия','LCA','LC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сен-Пьер И Микелон','Сен-Пьер и Микелон','SPM','PM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сент-Винсент И Гренадины','Сент-Винсент и Гренадины','VCT','VC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Сан-Марино','Сан-Марино','SMR','SM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Демократическая Республика Сан-Томе и Принсипи','Сан-Томе и Принсипи','STP','ST');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Саудовская Аравия','Саудовская Аравия ','SAU','SA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Сенегал','Сенегал ','SEN','SN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Сейшелы','Сейшелы ','SYC','SC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Сьерра-Леоне','Сьерра-Леоне','SLE','SL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Сингапур','Сингапур ','SGP','SG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Словацкая Республика','Словакия ','SVK','SK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Социалистическая Республика Вьетнам','Вьетнам','VNM','VN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Словения','Словения','SVN','SI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Федеративная Республика Сомали','Сомали','SOM','SO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Южно-Африканская Республика','Южная Африка','ZAF','ZA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Зимбабве','Зимбабве','ZWE','ZW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Испания','Испания','ESP','ES');
Insert into countries (name, short_name, iso_3, iso_2) values ('Западная Сахара','Западная Сахара','ESH','EH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Судан ','Судан','SDN','SD');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Суринам','Суринам','SUR','SR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Шпицберген и Ян-Майен','Шпицберген и Ян-Майен','SJM','SJ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Свазиленд ','Свазиленд','SWZ','SZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Швеция ','Швеция','SWE','SE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Швейцарская Конфедерация ','Швейцария','CHE','CH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сирийская Арабская Республика ','Сирийская Арабская Республика','SYR','SY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Таджикистан ','Таджикистан','TJK','TJ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Таиланд ','Таиланд','THA','TH');
Insert into countries (name, short_name, iso_3, iso_2) values ('Тоголезская Республика','Того','TGO','TG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Токелау','Токелау','TKL','TK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Королевство Тонга ','Тонга','TON','TO');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Тринидад и Тобаго','Тринидад и Тобаго','TTO','TT');
Insert into countries (name, short_name, iso_3, iso_2) values ('Объединенные Арабские Эмираты','Объединенные Арабские Эмираты','ARE','AE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Тунисская Республика ','Тунис','TUN','TN');
Insert into countries (name, short_name, iso_3, iso_2) values ('Турецкая Республика','Турция','TUR','TR');
Insert into countries (name, short_name, iso_3, iso_2) values ('Туркменистан','Туркменистан','TKM','TM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Острова Теркс и Кайкос','Острова Теркс и Кайкос','TCA','TC');
Insert into countries (name, short_name, iso_3, iso_2) values ('Тувалу','Тувалу','TUV','TV');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Уганда','Уганда','UGA','UG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Украина','Украина','UKR','UA');
Insert into countries (name, short_name, iso_3, iso_2) values ('Бывшая Югославская Республика Македония','Македония, бывшая Югославская Республика','MKD','MK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Арабская Республика Египет','Египет','EGY','EG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Соединенное Королевство Великобритании и Северной Ирландии','Соединенное Королевство Великобритании и Северной Ирландии','GBR','GB');
Insert into countries (name, short_name, iso_3, iso_2) values ('Объединенная Республика Танзания','Танзания, Объединенная Республика','TZA','TZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Соединенные Штаты Америки','Соединенные Штаты Америки','USA','US');
Insert into countries (name, short_name, iso_3, iso_2) values ('Виргинские Острова Соединенных Штатов','Виргинские Острова, США','VIR','VI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Буркина-Фасо','Буркина-Фасо','BFA','BF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Восточная Республика Уругвай ','Уругвай','URY','UY');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Узбекистан ','Узбекистан','UZB','UZ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Боливарианская Республика Венесуэла','Венесуэла, Боливарианская Республика','VEN','VE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Уоллис и Футуна','Уоллис и Футуна','WLF','WF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Независимое государство Самоа','Самоа','WSM','WS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Йемен','Йемен','YEM','YE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Замбия','Замбия','ZMB','ZM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Все','Все','Все','Вс');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Сербия','Сербия','SRB','RS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Черногория','Черногория','MNE','ME');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Южный Судан','Южный Судан','SSD','SS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Оккупированная Палестинская территория','Палестина, Государство','PS','PS');
Insert into countries (name, short_name, iso_3, iso_2) values ('Специальный административный регион Китая Гонконг','Гонконг','HKG','HK');
Insert into countries (name, short_name, iso_3, iso_2) values ('Бонэйр, Синт-Эстатиус и Саба','Бонэйр, Синт-Эстатиус и Саба','BES','BQ');
Insert into countries (name, short_name, iso_3, iso_2) values ('Гернси','Гернси','GGY','GG');
Insert into countries (name, short_name, iso_3, iso_2) values ('Джерси','Джерси','JEY','JE');
Insert into countries (name, short_name, iso_3, iso_2) values ('Республика Кот-д''Ивуар','Кот-д''Ивуар','CIV','CI');
Insert into countries (name, short_name, iso_3, iso_2) values ('Кюрасао','Кюрасао','CUW','CW');
Insert into countries (name, short_name, iso_3, iso_2) values ('Остров Мэн','Остров Мэн','IMN','IM');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сен Бартелеми','Сен Бартелеми','BLM','BL');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сен Мартин (французская часть)','Сен Мартин (французская часть)','MAF','MF');
Insert into countries (name, short_name, iso_3, iso_2) values ('Сен-Мартен (Нидерландская часть)','Сен-Мартен (Нидерландская часть)','SXM','SX');
Insert into countries (name, short_name, iso_3, iso_2) values ('Аландские острова','Аландские острова','ALA','AX');
