Insert into countries_groups (name, country_name) values ('СНГ','Азербайджан');
Insert into countries_groups (name, country_name) values ('СНГ','Армения');
Insert into countries_groups (name, country_name) values ('СНГ','Беларусь');
Insert into countries_groups (name, country_name) values ('СНГ','Казахстан');
Insert into countries_groups (name, country_name) values ('СНГ','Кыргызстан');
Insert into countries_groups (name, country_name) values ('СНГ','Молдова, Республика');
Insert into countries_groups (name, country_name) values ('СНГ','Российская Федерация');
Insert into countries_groups (name, country_name) values ('СНГ','Таджикистан');
Insert into countries_groups (name, country_name) values ('СНГ','Туркменистан');
Insert into countries_groups (name, country_name) values ('СНГ','Узбекистан');
Insert into countries_groups (name, country_name) values ('СНГ','Украина');
Insert into countries_groups (name, country_name) values ('Евразийский экономический союз','Российская Федерация');
Insert into countries_groups (name, country_name) values ('Евразийский экономический союз','Беларусь');
Insert into countries_groups (name, country_name) values ('Евразийский экономический союз','Казахстан');
Insert into countries_groups (name, country_name) values ('Евразийский экономический союз','Армения');
Insert into countries_groups (name, country_name) values ('Евразийский экономический союз','Кыргызстан');
Insert into countries_groups (name, country_name) values ('Соседи','Латвия');
Insert into countries_groups (name, country_name) values ('Соседи','Литва');
Insert into countries_groups (name, country_name) values ('Соседи','Польша');
Insert into countries_groups (name, country_name) values ('Соседи','Российская Федерация');
Insert into countries_groups (name, country_name) values ('Соседи','Украина');
Insert into countries_groups (name, country_name) values ('Европейский союз','Австрия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Бельгия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Болгария');
Insert into countries_groups (name, country_name) values ('Европейский союз','Соединенное Королевство Великобритании и Северной Ирландии');
Insert into countries_groups (name, country_name) values ('Европейский союз','Венгрия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Германия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Греция');
Insert into countries_groups (name, country_name) values ('Европейский союз','Дания');
Insert into countries_groups (name, country_name) values ('Европейский союз','Ирландия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Испания');
Insert into countries_groups (name, country_name) values ('Европейский союз','Италия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Кипр');
Insert into countries_groups (name, country_name) values ('Европейский союз','Латвия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Литва');
Insert into countries_groups (name, country_name) values ('Европейский союз','Люксембург');
Insert into countries_groups (name, country_name) values ('Европейский союз','Мальта');
Insert into countries_groups (name, country_name) values ('Европейский союз','Нидерланды');
Insert into countries_groups (name, country_name) values ('Европейский союз','Польша');
Insert into countries_groups (name, country_name) values ('Европейский союз','Португалия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Румыния');
Insert into countries_groups (name, country_name) values ('Европейский союз','Словакия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Словения');
Insert into countries_groups (name, country_name) values ('Европейский союз','Финляндия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Франция');
Insert into countries_groups (name, country_name) values ('Европейский союз','Хорватия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Чехия');
Insert into countries_groups (name, country_name) values ('Европейский союз','Швеция');
Insert into countries_groups (name, country_name) values ('Европейский союз','Эстония');
Insert into countries_groups (name, country_name) values ('Североамериканская зона свободной торговли (NAFTA)','Соединенные Штаты Америки');
Insert into countries_groups (name, country_name) values ('Североамериканская зона свободной торговли (NAFTA)','Канада');
Insert into countries_groups (name, country_name) values ('Североамериканская зона свободной торговли (NAFTA)','Мексика');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Австралия');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Бруней-Даруссалам');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Канада');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Индонезия');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Япония');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Корея, Республика');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Малайзия');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Новая Зеландия');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Филиппины');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Сингапур');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Таиланд');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Соединенные Штаты Америки');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Гонконг');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Китай');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Мексика');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Папуа-Новая Гвинея');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Чили');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Перу');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Российская Федерация');
Insert into countries_groups (name, country_name) values ('Азиатско-Тихоокеанское экономическое сотрудничество (АТЭС)','Вьетнам');
