INSERT INTO department (id, title, parent_id)  values (300, '-',0);
INSERT INTO department (id, title, parent_id)  values (301, 'Президент Республики Беларусь',300);
INSERT INTO department (id, title, parent_id)  values (302, 'Органы законодательной власти Республики Беларусь',300);
INSERT INTO department (id, title, parent_id)  values (303, 'Национальное собрание Республики Беларусь',302);
INSERT INTO department (id, title, parent_id)  values (304, 'Палата представителей Национального собрания Республики Беларусь',303);
INSERT INTO department (id, title, parent_id)  values (305, 'Совет Республики Национального собрания Республики Беларусь',303);
INSERT INTO department (id, title, parent_id)  values (306, 'Органы исполнительной власти Республики Беларусь',300);
INSERT INTO department (id, title, parent_id)  values (307, 'Совет Министров Республики Беларусь',306);
INSERT INTO department (id, title, parent_id)  values (308, 'Государственные органы и организации, подчиненные Президенту Республики Беларусь',306);
INSERT INTO department (id, title, parent_id)  values (309, 'Администрация Президента Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (310, 'Совет Безопасности Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (311, 'Управление делами Президента Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (312, 'Департамент по гуманитарной деятельности Управления делами Президента Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (313, 'Национальный статистический комитет Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (314, 'Следственный комитет Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (315, 'Государственный комитет судебных экспертиз Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (316, 'Государственная инспекция охраны животного и растительного мира при Президенте Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (317, 'Национальная академия наук Беларуси',308);
INSERT INTO department (id, title, parent_id)  values (318, 'Высшая аттестационная комиссия Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (319, 'Национальная государственная телерадиокомпания Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (320, 'Иные организации при Президенте Республики Беларусь',308);
INSERT INTO department (id, title, parent_id)  values (321, 'Государственные органы и организации, подчиненные Правительству Республики Беларусь',306);
INSERT INTO department (id, title, parent_id)  values (322, 'Аппарат Совета Министров Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (323, 'Министерство архитектуры и строительства Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (324, 'Министерство внутренних дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (325, 'Департамент исполнения наказаний Министерства внутренних дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (326, 'Департамент обеспечения оперативно-розыскной деятельности Министерства внутренних дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (327, 'Департамент охраны Министерства внутренних дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (328, 'Департамент по гражданству и миграции Министерства внутренних дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (329, 'Департамент финансов и тыла Министерства внутренних дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (330, 'Министерство жилищно-коммунального хозяйства Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (331, 'Министерство здравоохранения Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (332, 'Департамент фармацевтической промышленности Министерства здравоохранения Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (333, 'Министерство иностранных дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (334, 'Департамент внешнеэкономической деятельности Министерства иностранных дел Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (335, 'Министерство информации Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (336, 'Министерство культуры Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (337, 'Министерство лесного хозяйства Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (338, 'Министерство обороны Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (339, 'Департамент транспортного обеспечения Министерства обороны Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (340, 'Департамент международного военного сотрудничества Министерства обороны Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (341, 'Министерство образования Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (342, 'Департамент контроля качества образования Министерства образования Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (343, 'Министерство по налогам и сборам Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (344, 'Министерство по чрезвычайным ситуациям Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (345, 'Департамент по ликвидации последствий катастрофы на Чернобыльской АЭС Министерства по чрезвычайным ситуациям Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (346, 'Департамент по материальным резервам Министерства по чрезвычайным ситуациям Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (347, 'Департамент по надзору за безопасным ведением работ в промышленности Министерства по чрезвычайным ситуациям Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (348, 'Департамент по ядерной и радиационной безопасности Министерства по чрезвычайным ситуациям Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (349, 'Министерство природных ресурсов и охраны окружающей среды Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (350, 'Министерство промышленности Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (351, 'Министерство связи и информатизации Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (352, 'Департамент информатизации Министерства связи и информатизации Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (353, 'Министерство сельского хозяйства и продовольствия Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (354, 'Департамент ветеринарного и продовольственного надзора Министерства сельского хозяйства и продовольствия Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (355, 'Министерство спорта и туризма Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (356, 'Департамент по туризму Министерства спорта и туризма Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (357, 'Министерство антимонопольного регулирования и торговли Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (358, 'Министерство транспорта и коммуникаций Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (359, 'Департамент по авиации Министерства транспорта и коммуникаций Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (360, 'Министерство труда и социальной защиты Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (361, 'Департамент государственной инспекции труда Министерства труда и социальной защиты Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (362, 'Фонд социальной защиты населения Министерства труда и социальной защиты Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (363, 'Министерство финансов Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (364, 'Департамент государственных знаков Министерства финансов Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (365, 'Департамент по ценным бумагам Министерства финансов Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (366, 'Министерство экономики Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (367, 'Департамент по предпринимательству Министерства экономики Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (368, 'Департамент по санации и банкротству Министерства экономики Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (370, 'Министерство энергетики Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (371, 'Департамент по ядерной энергетике Министерства энергетики  Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (372, 'Министерство юстиции Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (373, 'Департамент по архивам и делопроизводству Министерства юстиции Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (374, 'Комитет государственной безопасности Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (375, 'Государственный военно-промышленный комитет Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (376, 'Государственный комитет по имуществу Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (377, 'Государственный комитет по науке и технологиям Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (378, 'Государственный комитет по стандартизации Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (379, 'Департамент контроля и надзора за строительством Государственного комитета по стандартизации Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (380, 'Департамент по энергоэффективности Государственного комитета по стандартизации Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (381, 'Государственный пограничный комитет Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (382, 'Государственный таможенный комитет Республики Беларусь',321);
INSERT INTO department (id, title, parent_id)  values (383, 'Белорусский государственный концерн пищевой промышленности &quot;Белгоспищепром&quot;',321);
INSERT INTO department (id, title, parent_id)  values (384, 'Белорусский государственный концерн по нефти и химии',321);
INSERT INTO department (id, title, parent_id)  values (385, 'Белорусский государственный концерн по производству и реализации товаров легкой промышленности',321);
INSERT INTO department (id, title, parent_id)  values (386, 'Белорусский производственно-торговый концерн лесной, деревообрабатывающей и целлюлозно-бумажной промышленности',321);
INSERT INTO department (id, title, parent_id)  values (387, 'Белорусский республиканский союз потребительских обществ',321);
INSERT INTO department (id, title, parent_id)  values (388, 'Республиканский центр по оздоровлению и санаторно-курортному лечению населения',321);
INSERT INTO department (id, title, parent_id)  values (389, 'Уполномоченный по делам религий и национальностей',321);
INSERT INTO department (id, title, parent_id)  values (390, 'Органы судебной власти Республики Беларусь',300);
INSERT INTO department (id, title, parent_id)  values (391, 'Конституционный Суд Республики Беларусь',390);
INSERT INTO department (id, title, parent_id)  values (392, 'Верховный Суд Республики Беларусь',390);
INSERT INTO department (id, title, parent_id)  values (393, 'Государственные органы Республики Беларусь с особым конституционно-правовым статусом',300);
INSERT INTO department (id, title, parent_id)  values (394, 'Органы государственного контроля и надзора',393);
INSERT INTO department (id, title, parent_id)  values (395, 'Прокуратура Республики Беларусь',394);
INSERT INTO department (id, title, parent_id)  values (396, 'Комитет государственного контроля Республики Беларусь',394);
INSERT INTO department (id, title, parent_id)  values (397, 'Департамент финансового мониторинга Комитета государственного контроля Республики Беларусь',394);
INSERT INTO department (id, title, parent_id)  values (398, 'Департамент финансовых расследований Комитета государственного контроля Республики Беларусь',394);
INSERT INTO department (id, title, parent_id)  values (399, 'Иные государственные органы с особым конституционно-правовым статусом',393);
INSERT INTO department (id, title, parent_id)  values (400, 'Национальный банк Республики Беларусь',399);
INSERT INTO department (id, title, parent_id)  values (401, 'Центральная комиссия Республики Беларусь по выборам и проведению республиканских референдумов',399);
INSERT INTO department (id, title, parent_id)  values (402, 'Органы местного управления и самоуправления Республики Беларусь',300);
INSERT INTO department (id, title, parent_id)  values (403, 'Местные Советы депутатов',402);
INSERT INTO department (id, title, parent_id)  values (404, 'Областные (Минский городской) Советы депутатов',403);
INSERT INTO department (id, title, parent_id)  values (405, 'Городские (городов областного подчинения) и районные Советы депутатов',403);
INSERT INTO department (id, title, parent_id)  values (406, 'Городские (городов районного подчинения), поселковые и сельские Советы депутатов',403);
INSERT INTO department (id, title, parent_id)  values (407, 'Местные исполнительные и распорядительные органы',402);
INSERT INTO department (id, title, parent_id)  values (408, 'Областные (Минский городской) исполнительные комитеты',407);
INSERT INTO department (id, title, parent_id)  values (409, 'Городские (городов областного подчинения) и районные исполнительные комитеты',407);
INSERT INTO department (id, title, parent_id)  values (410, 'Городские (городов районного подчинения), поселковые, сельские исполнительные комитеты, местные администрации',407);
INSERT INTO department (id, title, parent_id)  values (411, 'Межгосударственные органы управления',300);
INSERT INTO department (id, title, parent_id)  values (412, 'Исполнительный комитет Содружества Независимых Государств',411);
INSERT INTO department (id, title, parent_id)  values (413, 'Иные органы наднационального характера',411);
INSERT INTO department (id, title, parent_id)  values (414, 'Группировки субъектов, не относящихся к органам государственной власти и управления',300);
INSERT INTO department (id, title, parent_id)  values (415, 'Администрации свободных экономических зон',414);
INSERT INTO department (id, title, parent_id)  values (416, 'Государственное учреждение «Администрация свободной экономической зоны &quot;Брест&quot;»',415);
INSERT INTO department (id, title, parent_id)  values (417, 'Государственное учреждение «Администрация свободной экономической зоны &quot;Витебск&quot;»',415);
INSERT INTO department (id, title, parent_id)  values (418, 'Государственное учреждение «Администрация свободной экономической зоны &quot;Гомель-Ратон&quot;»',415);
INSERT INTO department (id, title, parent_id)  values (419, 'Государственное учреждение «Администрация свободной экономической зоны &quot;Гродноинвест&quot;»',415);
INSERT INTO department (id, title, parent_id)  values (420, 'Государственное учреждение «Администрация свободной экономической зоны &quot;Минск&quot;»',415);
INSERT INTO department (id, title, parent_id)  values (421, 'Государственное учреждение «Администрация свободной экономической зоны &quot;Могилев&quot;»',415);
INSERT INTO department (id, title, parent_id)  values (422, 'Государственное учреждение &quot;Администрация Парка высоких технологий&quot;',414);
INSERT INTO department (id, title, parent_id)  values (423, 'Общественные организации (объединения)',414);
INSERT INTO department (id, title, parent_id)  values (424, 'Религиозные организации (объединения)',414);
INSERT INTO department (id, title, parent_id)  values (425, 'Республиканские государственно-общественные объединения',414);
INSERT INTO department (id, title, parent_id)  values (426, 'Юридические лица без ведомственной подчиненности (кроме общественных, религиозных организаций (объединений), республиканских государственно-общественных объединений)',414);
INSERT INTO department (id, title, parent_id)  values (427, 'Банки',426);
INSERT INTO department (id, title, parent_id)  values (428, 'Прочие юридические лица без ведомственной подчиненности',426);
INSERT INTO department (id, title, parent_id)  values (429, 'Индивидуальные предприниматели',414);
INSERT INTO department (id, title, parent_id)  values (430, 'Физические лица',300);
INSERT INTO department (id, title, parent_id)  values (431, 'Нерезиденты Республики Беларусь',300);