export const PROCURING_ENT_DATES_COUNT_REQUEST = 'PROCURING_ENT_DATES_COUNT_REQUEST'
export const PROCURING_ENT_DATES_COUNT_SUCCESS = 'PROCURING_ENT_DATES_COUNT_SUCCESS'
export const PROCURING_ENT_DATES_COUNT_FAILURE = 'PROCURING_ENT_DATES_COUNT_FAILURE'
export const PROCURING_ENT_DATES_COUNT_CLEAR = 'PROCURING_ENT_DATES_COUNT_CLEAR'

export const SUPPLIERS_DATES_COUNT_REQUEST = 'SUPPLIERS_DATES_COUNT_REQUEST'
export const SUPPLIERS_DATES_COUNT_SUCCESS = 'SUPPLIERS_DATES_COUNT_SUCCESS'
export const SUPPLIERS_DATES_COUNT_FAILURE = 'SUPPLIERS_DATES_COUNT_FAILURE'
export const SUPPLIERS_DATES_COUNT_CLEAR = 'SUPPLIERS_DATES_COUNT_CLEAR'

export const LOTS_COMPLETE_DATES_COUNT_REQUEST = 'LOTS_COMPLETE_DATES_COUNT_REQUEST'
export const LOTS_COMPLETE_DATES_COUNT_SUCCESS = 'LOTS_COMPLETE_DATES_COUNT_SUCCESS'
export const LOTS_COMPLETE_DATES_COUNT_FAILURE = 'LOTS_COMPLETE_DATES_COUNT_FAILURE'
export const LOTS_COMPLETE_DATES_COUNT_CLEAR = 'LOTS_COMPLETE_DATES_COUNT_CLEAR'

export const LOTS_ACTIVE_DATES_COUNT_REQUEST = 'LOTS_ACTIVE_DATES_COUNT_REQUEST'
export const LOTS_ACTIVE_DATES_COUNT_SUCCESS = 'LOTS_ACTIVE_DATES_COUNT_SUCCESS'
export const LOTS_ACTIVE_DATES_COUNT_FAILURE = 'LOTS_ACTIVE_DATES_COUNT_FAILURE'
export const LOTS_ACTIVE_DATES_COUNT_CLEAR = 'LOTS_ACTIVE_DATES_COUNT_CLEAR'

export const PROCEDURES_TOP_REQUEST = 'PROCEDURES_TOP_REQUEST'
export const PROCEDURES_TOP_SUCCESS = 'PROCEDURES_TOP_SUCCESS'
export const PROCEDURES_TOP_FAILURE = 'PROCEDURES_TOP_FAILURE'
export const PROCEDURES_TOP_CLEAR = 'PROCEDURES_TOP_CLEAR'

export const PROCEDURES_SINGLE_SOURCE_TOP_REQUEST = 'PROCEDURES_SINGLE_SOURCE_TOP_REQUEST'
export const PROCEDURES_SINGLE_SOURCE_TOP_SUCCESS = 'PROCEDURES_SINGLE_SOURCE_TOP_SUCCESS'
export const PROCEDURES_SINGLE_SOURCE_TOP_FAILURE = 'PROCEDURES_SINGLE_SOURCE_TOP_FAILURE'
export const PROCEDURES_SINGLE_SOURCE_TOP_CLEAR = 'PROCEDURES_SINGLE_SOURCE_TOP_CLEAR'

export const OKRB_TOP_REQUEST = 'OKRB_TOP_REQUEST'
export const OKRB_TOP_SUCCESS = 'OKRB_TOP_SUCCESS'
export const OKRB_TOP_FAILURE = 'OKRB_TOP_FAILURE'
export const OKRB_TOP_CLEAR = 'OKRB_TOP_CLEAR'

export const ENQUIRIES_COUNT_REQUEST = 'ENQUIRIES_COUNT_REQUEST'
export const ENQUIRIES_COUNT_SUCCESS = 'ENQUIRIES_COUNT_SUCCESS'
export const ENQUIRIES_COUNT_FAILURE = 'ENQUIRIES_COUNT_FAILURE'
export const ENQUIRIES_COUNT_CLEAR = 'ENQUIRIES_COUNT_CLEAR'

export const KPI_CONTRACTS_COUNT_REQUEST = 'KPI_CONTRACTS_COUNT_REQUEST'
export const KPI_CONTRACTS_COUNT_SUCCESS = 'KPI_CONTRACTS_COUNT_SUCCESS'
export const KPI_CONTRACTS_COUNT_FAILURE = 'KPI_CONTRACTS_COUNT_FAILURE'
export const KPI_CONTRACTS_COUNT_CLEAR = 'KPI_CONTRACTS_COUNT_CLEAR'

export const KPI_CONTRACTS_AMOUNT_REQUEST = 'KPI_CONTRACTS_AMOUNT_REQUEST'
export const KPI_CONTRACTS_AMOUNT_SUCCESS = 'KPI_CONTRACTS_AMOUNT_SUCCESS'
export const KPI_CONTRACTS_AMOUNT_FAILURE = 'KPI_CONTRACTS_AMOUNT_FAILURE'
export const KPI_CONTRACTS_AMOUNT_CLEAR = 'KPI_CONTRACTS_AMOUNT_CLEAR'

export const PROCEDURES_SUCCESSFUL_COUNT_REQUEST = 'PROCEDURES_SUCCESSFUL_COUNT_REQUEST'
export const PROCEDURES_SUCCESSFUL_COUNT_SUCCESS = 'PROCEDURES_SUCCESSFUL_COUNT_SUCCESS'
export const PROCEDURES_SUCCESSFUL_COUNT_FAILURE = 'PROCEDURES_SUCCESSFUL_COUNT_FAILURE'
export const PROCEDURES_SUCCESSFUL_COUNT_CLEAR = 'PROCEDURES_SUCCESSFUL_COUNT_CLEAR'

export const PROCEDURES_AVG_PER_HOUR_REQUEST = 'PROCEDURES_AVG_PER_HOUR_REQUEST'
export const PROCEDURES_AVG_PER_HOUR_SUCCESS = 'PROCEDURES_AVG_PER_HOUR_SUCCESS'
export const PROCEDURES_AVG_PER_HOUR_FAILURE = 'PROCEDURES_AVG_PER_HOUR_FAILURE'
export const PROCEDURES_AVG_PER_HOUR_CLEAR = 'PROCEDURES_AVG_PER_HOUR_CLEAR'

export const PROCEDURES_COMPETETIVE_EVERY_N_REQUEST = 'PROCEDURES_COMPETETIVE_EVERY_N_REQUEST'
export const PROCEDURES_COMPETETIVE_EVERY_N_SUCCESS = 'PROCEDURES_COMPETETIVE_EVERY_N_SUCCESS'
export const PROCEDURES_COMPETETIVE_EVERY_N_FAILURE = 'PROCEDURES_COMPETETIVE_EVERY_N_FAILURE'
export const PROCEDURES_COMPETETIVE_EVERY_N_CLEAR = 'PROCEDURES_COMPETETIVE_EVERY_N_CLEAR'

export const CONTRACTS_COMMON_INFO_REQUEST = 'CONTRACTS_COMMON_INFO_REQUEST'
export const CONTRACTS_COMMON_INFO_SUCCESS = 'CONTRACTS_COMMON_INFO_SUCCESS'
export const CONTRACTS_COMMON_INFO_FAILURE = 'CONTRACTS_COMMON_INFO_FAILURE'
export const CONTRACTS_COMMON_INFO_CLEAR = 'CONTRACTS_COMMON_INFO_CLEAR'
